name: are_you_ok
description: "木鱼"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  # 音频播放
  audioplayers: ^6.5.0
  # audioplayers:
  # git:
  # url: https://gitcode.com/openharmony-sig/flutter_audioplayers.git
  # path: packages/audioplayers
  flutter_svg: ^2.0.9 # svg
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sound/
